### ISSUE TITLE
ImportError: No module named dobject.groupthink

### ISSUE THREAD

**Issue by yell0wfl4sh** [sugarlabs/arithmetic#3]
The error is logged on running this activity.

**Comment by quozl** [comment]
As the `dobject` directory is a git submodule, please verify that you used `git clone --recursive` or the Arithmetic bundle file from activities.sugarlabs.org.

We often have problems reported with submodules caused by not cloning recursively.  Perhaps we should include the source instead of using a submodule.

**Comment by yell0wfl4sh** [comment]
@quozl  I am facing some difficulties while porting dobject to Gtk+3, I don't know the equivalent of `GenericTreeView` in Gtk+3, so I am kinda stuck here, please tell me if you know anything about it, thanks.
For more info, see: https://github.com/yashagrawal3/arithmetic/tree/gtk3

**Comment by chimosky** [comment]
@yashagrawal3 does activity run or error is thrown, and an error log would be helpful.

**Comment by yell0wfl4sh** [comment]
@chimosky here:
```
Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 220, in <module>
    main()
  File "/usr/bin/sugar-activity", line 164, in main
    module = __import__(module_name)
  File "/home/yash/gssoc/arithmetic/arithmetic.py", line 27, in <module>
    import dobject.groupthink.gtk_tools as gtk_tools
  File "/home/yash/gssoc/arithmetic/dobject/groupthink/gtk_tools.py", line 84, in <module>
    class SharedTreeStore(groupthink.CausalHandlerAcceptor, Gtk.TreeModel):
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 214, in __init__
    super(GObjectMeta, cls).__init__(name, bases, dict_)
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 193, in __init__
    cls._type_register(cls.__dict__)
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 205, in _type_register
    _gobject.type_register(cls, namespace.get('__gtype_name__'))
TypeError: Error when calling the metaclass bases
    argument must be a GObject subclass

```

**Comment by chimosky** [comment]
@yashagrawal3 seems your version isn't the same as the one in https://github.com/yashagrawal3/arithmetic/tree/gtk3

**Comment by yell0wfl4sh** [comment]
sorry, please recheck.

**Comment by quozl** [comment]
@yashagrawal3, sorry, I don't know anything about GenericTreeView.  Check the GTK+ 2 and GTK+ 3 documentation?

**Comment by quozl** [comment]
GroupThink is in the StopWatch activity too.

**Comment by Paroksh1** [comment]
Hi! @quozl 
I have raised PR for this issue, 
This PR fixes the import error caused by the missing `dobject` submodule. Instead of a cryptic traceback, users will now get a clear message on how to resolve it. I’ve also kept the changes scoped only to `arithmetic.py`.

Let me know if any changes are needed — happy to iterate further!

**Comment by quozl** [comment]
No, port to GTK 3 first, assess whether the module is still required, and if so vendor it from StopWatch.
