### ISSUE TITLE
Port to GTK+ 3

### ISSUE THREAD

**Issue by quozl** [sugarlabs/arithmetic#4]

**Comment by abhishektanwar** [comment]
@quozl I want to contribute to this activity and port it to GTK +3

**Comment by quozl** [comment]
That's great, thanks.

**Comment by abhishektanwar** [comment]
@quozl I started to port this activity to GTK+3 ,when I ran it on my sugar desktop it didn't work and following errors were obtained in log file.

<type 'exceptions.ImportError'>
Python 2.7.17: /usr/bin/python
Thu Jan 23 04:13:18 2020

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /usr/bin/sugar-activity in <module>()
  215 
  216     if hasattr(instance, 'run_main_loop'):
  217         instance.run_main_loop()
  218 
  219 main()
main = <function main>

 /usr/bin/sugar-activity in main()
  161     class_name = splitted_module[1]
  162 
  163     module = __import__(module_name)
  164     for comp in module_name.split('.')[1:]:
  165         module = getattr(module, comp)
module undefined
builtin__import__ = <built-in function __import__>
module_name = 'arithmetic'

 /usr/share/sugar/activities/Arithmetic.activity/arithmetic.py in <module>()
   15 
   16 import logging
   17 import gtk
   18 import pango
   19 import random
gtk undefined
<type 'exceptions.ImportError'>: No module named gtk
    __class__ = <type 'exceptions.ImportError'>
    __delattr__ = <method-wrapper '__delattr__' of exceptions.ImportError object>
    __dict__ = {}
    __doc__ = "Import can't find module, or can't find name in module."
    __format__ = <built-in method __format__ of exceptions.ImportError object>
    __getattribute__ = <method-wrapper '__getattribute__' of exceptions.ImportError object>
    __getitem__ = <method-wrapper '__getitem__' of exceptions.ImportError object>
    __getslice__ = <method-wrapper '__getslice__' of exceptions.ImportError object>
    __hash__ = <method-wrapper '__hash__' of exceptions.ImportError object>
    __init__ = <method-wrapper '__init__' of exceptions.ImportError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of exceptions.ImportError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of exceptions.ImportError object>
    __repr__ = <method-wrapper '__repr__' of exceptions.ImportError object>
    __setattr__ = <method-wrapper '__setattr__' of exceptions.ImportError object>
    __setstate__ = <built-in method __setstate__ of exceptions.ImportError object>
    __sizeof__ = <built-in method __sizeof__ of exceptions.ImportError object>
    __str__ = <method-wrapper '__str__' of exceptions.ImportError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __unicode__ = <built-in method __unicode__ of exceptions.ImportError object>
    args = ('No module named gtk',)
    message = 'No module named gtk'

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 219, in <module>
    main()
  File "/usr/bin/sugar-activity", line 163, in main
    module = __import__(module_name)
  File "/usr/share/sugar/activities/Arithmetic.activity/arithmetic.py", line 17, in <module>
    import gtk
ImportError: No module named gtk


Exited with status 1, pid 1675 data (<open file '<fdopen>', mode 'w' at 0x7f28d7dbc780>, 'e1df43f3e9571a85b2dc8b025ba334c83eff39ea')

This is my first time contributing to such a big organization and I cannot figure out how to approach these errors and move forward by making changes and getting the desired results.
Any input from you would be very valueable to me.
Thanks
[arithmetic.txt](https://github.com/sugarlabs/arithmetic/files/4100892/arithmetic.txt)

**Comment by chimosky** [comment]
@abhishektanwar when porting, all occurences of `import gtk` become `from gi.repository import Gtk`.
See our [GTK3 porting guide](https://github.com/sugarlabs/sugar-docs/blob/master/src/gtk3-porting-guide.md) for the changes that need to be made.

**Comment by quozl** [comment]
You should also test it with GTK 2 first, so you know what it is meant to look like; otherwise it would by like flying an airplane with eyes closed.

**Comment by quozl** [comment]
Reference to a [related mailing list thread](http://lists.sugarlabs.org/archive/sugar-devel/2020-January/057696.html).
